before_commands:
    - "composer install --no-interaction"
build:
  nodes:
    php70:
      environment:
        php: 7.0
    php71:
      environment:
        php: 7.1
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit
            coverage:
              file: build/logs/clover.xml                                        
              format: clover
checks:
    php: true