before_commands:
    - "composer install --no-interaction"
build:
  nodes:
    coverage:
      tests:
        override:
          - command: vendor/bin/phpunit
            coverage:
              file: build/logs/clover.xml                                        
              format: clover